//! 更新默认主题配置后，需要执行 npm run build:theme 重新构建index.json

const fs = require('fs')
const path = require('path')
const { createThemeColors } = require('./utils')

const solidLight = (primary, extra = {}) => ({
  primary,
  font: 'rgb(33, 33, 33)',
  '--color-app-background': '#f5f5f7',
  '--color-nav-background': 'transparent',
  '--color-main-background': 'rgba(255, 255, 255, 0.94)',
  '--color-nav-font': 'var(--color-650)',
  '--background-image': 'none',
  '--background-image-position': 'center',
  '--background-image-size': 'cover',
  '--color-btn-hide': '#b9b9be',
  '--color-btn-min': '#b9b9be',
  '--color-btn-close': '#fa5f57',
  '--color-badge-primary': 'var(--color-primary)',
  '--color-badge-secondary': '#0a84ff',
  '--color-badge-tertiary': '#ff9f0a',
  ...extra,
})

const solidDark = (primary, extra = {}) => ({
  primary,
  font: 'rgb(229, 229, 229)',
  '--color-app-background': 'rgba(22, 22, 24, 1)',
  '--color-nav-background': 'transparent',
  '--color-main-background': 'rgba(28, 28, 30, 0.94)',
  '--color-nav-font': 'var(--color-650)',
  '--background-image': 'none',
  '--background-image-position': 'center',
  '--background-image-size': 'cover',
  '--color-btn-hide': '#636366',
  '--color-btn-min': '#636366',
  '--color-btn-close': '#ff5f57',
  '--color-badge-primary': 'var(--color-primary)',
  '--color-badge-secondary': '#0a84ff',
  '--color-badge-tertiary': '#ff9f0a',
  ...extra,
})

const pictureLight = (primary, image, extra = {}) => ({
  primary,
  font: 'rgb(33, 33, 33)',
  '--color-app-background': 'transparent',
  '--color-nav-background': 'rgba(255, 255, 255, 0.42)',
  '--color-main-background': 'rgba(255, 255, 255, 0.18)',
  '--color-nav-font': 'var(--color-850)',
  '--background-image': `url(./theme_images/${image})`,
  '--background-image-position': 'center',
  '--background-image-size': 'cover',
  '--color-btn-hide': '#b9b9be',
  '--color-btn-min': '#b9b9be',
  '--color-btn-close': '#fa5f57',
  '--color-badge-primary': 'var(--color-primary)',
  '--color-badge-secondary': '#0a84ff',
  '--color-badge-tertiary': '#ff9f0a',
  ...extra,
})

const pictureDark = (primary, image, extra = {}) => ({
  primary,
  font: 'rgb(229, 229, 229)',
  '--color-app-background': 'transparent',
  '--color-nav-background': 'rgba(18, 18, 20, 0.42)',
  '--color-main-background': 'rgba(18, 18, 20, 0.18)',
  '--color-nav-font': 'var(--color-200)',
  '--background-image': `url(./theme_images/${image})`,
  '--background-image-position': 'center',
  '--background-image-size': 'cover',
  '--color-btn-hide': '#636366',
  '--color-btn-min': '#636366',
  '--color-btn-close': '#ff5f57',
  '--color-badge-primary': 'var(--color-primary)',
  '--color-badge-secondary': '#64d2ff',
  '--color-badge-tertiary': '#ffd60a',
  ...extra,
})

const defaultThemes = [
  {
    id: 'red_light',
    name: '绯红·亮',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(250, 45, 72)'),
  },
  {
    id: 'red_dark',
    name: '绯红·暗',
    isDark: true,
    isDarkFont: false,
    config: solidDark('rgb(255, 69, 88)'),
  },
  {
    id: 'green',
    name: '绿意盎然',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(52, 199, 89)'),
  },
  {
    id: 'blue',
    name: '蓝田生玉',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(10, 132, 255)'),
  },
  {
    id: 'blue_plus',
    name: '蛋雅深蓝',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(90, 141, 238)'),
  },
  {
    id: 'orange',
    name: '橙黄橘绿',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(255, 149, 0)'),
  },
  {
    id: 'red',
    name: '热情似火',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(255, 59, 48)'),
  },
  {
    id: 'pink',
    name: '粉装玉琢',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(255, 45, 85)'),
  },
  {
    id: 'purple',
    name: '重斤球紫',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(175, 82, 222)'),
  },
  {
    id: 'grey',
    name: '灰常美丽',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(142, 142, 147)'),
  },
  {
    id: 'ming',
    name: '青出于黑',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(48, 176, 199)'),
  },
  {
    id: 'blue2',
    name: '清热板蓝',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(94, 92, 230)'),
  },
  {
    id: 'teal',
    name: '青绿',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(13, 148, 136)'),
  },
  {
    id: 'mint',
    name: '薄荷',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(32, 178, 170)'),
  },
  {
    id: 'sand',
    name: '沙色',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(196, 140, 84)'),
  },
  {
    id: 'lavender',
    name: '薰衣草',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(139, 127, 232)'),
  },
  {
    id: 'coral',
    name: '珊瑚',
    isDark: false,
    isDarkFont: false,
    config: solidLight('rgb(255, 107, 107)'),
  },
  {
    id: 'nord',
    name: '极光',
    isDark: true,
    isDarkFont: false,
    config: solidDark('rgb(136, 192, 208)', {
      '--color-app-background': 'rgba(46, 52, 64, 1)',
      '--color-main-background': 'rgba(59, 66, 82, 0.94)',
    }),
  },
  {
    id: 'midnight',
    name: '夜蓝',
    isDark: true,
    isDarkFont: false,
    config: solidDark('rgb(99, 102, 241)', {
      '--color-app-background': 'rgba(15, 16, 28, 1)',
      '--color-main-background': 'rgba(24, 26, 42, 0.94)',
    }),
  },
  {
    id: 'black',
    name: '黑灯瞎火',
    isDark: true,
    isDarkFont: false,
    config: pictureDark('rgb(180, 180, 184)', 'landingMoon.png'),
  },
  {
    id: 'mid_autumn',
    name: '月里嫦娥',
    isDark: true,
    isDarkFont: false,
    config: pictureDark('rgb(232, 154, 184)', 'jqbg.jpg'),
  },
  {
    id: 'naruto',
    name: '木叶之村',
    isDark: false,
    isDarkFont: false,
    config: pictureLight('rgb(56, 152, 196)', 'myzcbg.jpg'),
  },
  {
    id: 'china_ink',
    name: '近墨者黑',
    isDark: false,
    isDarkFont: false,
    config: pictureLight('rgb(62, 78, 68)', 'china_ink.jpg', {
      '--color-badge-primary': 'rgba(137, 70, 70, 1)',
      '--color-badge-secondary': 'rgba(67, 139, 65, 1)',
      '--color-badge-tertiary': 'rgba(132, 135, 65, 1)',
    }),
  },
  {
    id: 'happy_new_year',
    name: '新年快乐',
    isDark: false,
    isDarkFont: false,
    config: pictureLight('rgb(200, 48, 40)', 'xnkl.png'),
  },
  {
    id: 'rainy',
    name: '听雨',
    isDark: true,
    isDarkFont: false,
    config: pictureDark('rgb(120, 168, 214)', 'rainy_city.jpg'),
  },
  {
    id: 'dusk',
    name: '暮海',
    isDark: false,
    isDarkFont: false,
    config: pictureLight('rgb(232, 140, 72)', 'dusk_sea.jpg'),
  },
  {
    id: 'aurora',
    name: '极光林',
    isDark: true,
    isDarkFont: false,
    config: pictureDark('rgb(72, 214, 156)', 'aurora_sky.jpg'),
  },
  {
    id: 'lake',
    name: '山湖',
    isDark: false,
    isDarkFont: false,
    config: pictureLight('rgb(32, 158, 168)', 'mountain_lake.jpg'),
  },
  {
    id: 'meadow',
    name: '手绘原野',
    isDark: false,
    isDarkFont: false,
    config: pictureLight('rgb(214, 154, 64)', 'anime_sky.jpg'),
  },
  {
    id: 'cottage',
    name: '乡云',
    isDark: false,
    isDarkFont: false,
    config: pictureLight('rgb(88, 156, 92)', 'country_tree.jpg'),
  },
]

const themes = defaultThemes.map(({ config: { primary, font, ...extInfo }, ...themeInfo }) => {
  return {
    ...themeInfo,
    isCustom: false,
    config: {
      themeColors: createThemeColors(primary, font, themeInfo.isDark),
      extInfo,
    },
  }
})

fs.writeFileSync(path.join(__dirname, 'index.json'), JSON.stringify(themes, null, 2))
